meta_product_name: "Fivelines"
meta_title: "Fivelines - The music sounds better with you"
meta_description: "A music education app for music teachers"
meta_image: "cover.png" # should exist in `app/assets/images/`
